### ISSUE TITLE
Handle side effects with Mavericks

### ISSUE THREAD

**Issue by varo610** [airbnb/mavericks#532]
I'm trying to manage ViewModel side effects and I didn't find the proper way of doing it with Mavericks.

Basically I have a sealed class with side effects, for example:

```
sealed class XScreenSideEffects(){
	data class ShowToast(val text: String): XScreenSideEffects()
	object class NavigateToScreenY: XScreenSideEffects()
}
```

I tried having a property on the state and use `selectSubscribe` with `deliveryMode = uniqueOnly()`:

```
data class XScreenState(

	...
	
	val sideEffects: XScreenSideEffects
): MavericksState
```

The issue is ShowToast side effect can we triggered 2 times in a row. 

For example on a screen with a submit button we want to show a toast if one of the fields is empty:

- The user taps submit button when one field is empty and we show toast/snackbar
- The toast/snackbar dissapears
- The user taps again the button without updating anything 
- We want to show the same toast/snackbar 

That second toast is not shown cause Mavericks ignore the change on the state.

I tried using `stateFlow` without `.distinctUntilChanged()` but as the documentation indicates `StateFlow` already behaves as if `distinctUtilChanged` operator is applied to it.

Any ideas on how to achieve this?

Thank you

**Comment by franciscoaleixo** [comment]
I think you're misunderstanding the use of uniqueOnly. At the end of the day, you're observing a state, and you're not changing the state by sending two ShowToast with the same text in a row, so nothing will happen. I think the idea with Mavericks is that there are no side effects. The issue with this is that sometimes you want to execute an action based on a state change, but you definitely don't want to recreate that action after a configuration change -- uniqueOnly addresses this (e.g. showing a toast). Correct me if I'm wrong though @elihart @gpeal 

Having that said, here's some suggestions to accomplish what you want:
- Create a state property for the submission. Here you can wrap this with Async, since I'm assuming the submission will either be succesful, fail, and in the meanwhile will be loading. You'll then subscribe to this with uniqueOnly for the toast action if the state property is in the fail state.
- If you really like the idea of having side effects, you could have a separate flow for this. There's resources out there that explore different options, but a common approach is to either use a Channel and convert it to a flow, or straight-up use a SharedFlow (there's pros and cons with each), [here's an article](https://proandroiddev.com/android-singleliveevent-redux-with-kotlin-flow-b755c70bb055) with the Channel approach.
- Alternatively, you could forego the idea of having a toast and simply make it so that the submit button is not clickable while the fields are empty, this might be a better overall approach but I realize this was not the intent of the question though.

**Comment by franciscoaleixo** [comment]
I think you're misunderstanding the use of uniqueOnly. At the end of the day, you're observing a state, and you're not changing the state by sending two ShowToast with the same text in a row, so nothing will happen. I think the idea with Mavericks is that there are no side effects. The issue with this is that sometimes you want to execute an action (e.g. showing a toast) based on a state change, but you definitely don't want to recreate that action after a configuration change -- uniqueOnly addresses this. Correct me if I'm wrong though @elihart @gpeal 

Having that said, here's some suggestions to accomplish what you want:
- Create a state property for the submission. Here you can wrap this with Async, since I'm assuming the submission will either be succesful, fail, and in the meanwhile will be loading. You'll then subscribe to this with uniqueOnly for the toast action if the state property is in the fail state.
- If you really like the idea of having side effects, you could have a separate flow for this. There's resources out there that explore different options, but a common approach is to either use a Channel and convert it to a flow, or straight-up use a SharedFlow (there's pros and cons with each), [here's an article](https://proandroiddev.com/android-singleliveevent-redux-with-kotlin-flow-b755c70bb055) with the Channel approach.
- Alternatively, you could forego the idea of having a toast and simply make it so that the submit button is not clickable while the fields are empty, this might be a better overall approach but I realize this was not the intent of the question though.

**Comment by varo610** [comment]
@franciscoaleixo Thanks for the help

Since MvRx 1.x we are using an Async to handle side effects, something like this:
```
Single.just(ShowToast("X")).execute{copy(sideEffects=it)}
```

But I was wondering if 2.0 allow us to do something similar in a less hacky way.

**Comment by franciscoaleixo** [comment]
@varo610 I agree that your approach is hacky but it is so because you're trying to force side effects onto Mavericks when it wasn't meant to be used that way. If your view calls `viewModel.submit(params...)` on Submit click, your view model should then process that submission and expose the state of that submission (e.g. on the View State `val submissionAsync: Async<SubmitResult>`). Then you would observe this property on the view and act accordingly. If you know you want a toast on fail, you'll use uniqueOnly when subscribing to that state to show that toast. That's it, you don't need a separate side effect for this.

**Comment by varo610** [comment]
@franciscoaleixo I understand what you mean. 

The submit case was just a simple example. I general we have business logic that trigger different side effects and we want to have it on the ViewModel/UseCases in order to unit test it.

**Comment by gpeal** [comment]
@varo610 You can generally get creative with how you use state to achieve pretty much whateer you want. I've seen cases where you have an error/toast state and then once it has been displayed, the callback calls a function on the view model to clear the state so that it can be triggered again.

**Comment by varo610** [comment]
Thank you both for the help, we will find a way of doing it :)

**Comment by gpeal** [comment]
@varo610 Another option is to have a separate `SharedFlow` property on your ViewModel that you handle however you'd like.

**Comment by varo610** [comment]
Thanks @gpeal That sounds good :)
