### ISSUE TITLE
Some actions can't be reached in some states

### ISSUE THREAD

**Issue by GrahamBorland** [airbnb/mavericks#555]
Hi! I'm new to Mavericks. I'm really enjoying playing with it so far!

I imagine it's quite common to express state as a sealed class hierarchy.

```kotlin
sealed class AdvancedOptionsState : MavericksState{
    object Loading : AdvancedOptionsState()
    data class Error(val message: String) : AdvancedOptionsState()
    data class Success(val items: List<AdvancedOptionsItem>) : AdvancedOptionsState()
}
```

Some actions only make sense in the context of a specific state. For example, it's only possible to call `toggleItem` when I know I'm in the `Success` state.

```kotlin
class AdvancedOptionsViewModel :
    MavericksViewModel<AdvancedOptionsState>(AdvancedOptionsState.Loading) {

    fun toggleItem(item: AdvancedOptionsItem) {
        setState {
            when (this) {
                is AdvancedOptionsState.Error -> throw IllegalStateException("Should never get here")
                AdvancedOptionsState.Loading -> throw IllegalStateException("Should never get here")
                is AdvancedOptionsState.Success -> {
                    copy(...)
                }
            }
        }
    }
}
```
I couldn't see a nice way to express this in Mavericks. The result is that all my action/intent functions have to be defensive and check for all the illegal state combinations, and either log the illegal state or throw an exception.

We end up with a combinatorial explosion of possible actions and states, even though only a tiny subset of those combinations are actually valid and can ever happen in reality.

Is there a better way to express the relationship between actions and a subset of the available states, or do I just have to put up with empty/unreachable branches in all of my `when` expressions?

Would something like this be feasible?
```kotlin
fun toggleItem(item: AdvancedOptionsItem) {
    setState<AdvancedOptionsState.Success> {
        // this is only called when the current state is AdvancedOptionsState.Success             
        copy(...)
    }
}
```

**Comment by gpeal** [comment]
@GrahamBorland Actually, it is quite uncommon to make MavericksState a sealed class. It is more common to do something like:
```
data class AdvancedOptionsState(
    val options: Async<List<AdvancedOptionsItem>> = Uninitialized,
    val toggledOptionIds: Set<String> = emptySet(),
) : MavericksState {
    val toggledOptions = options.filter { it.id in toggledOptionIds }
}

class ViewModel(..., optionsReopsitory: OptionsRepository) : ... {
    init {
        optionsRepository.options.execute { copy(options = it) }
    }

    fun toggleItem(item: AdvancedOptionItem) {
        setState { 
            copy(toggledOptionIds = if (it.id in toggledOptionIds) toggledOptionIds - item.id else toggleOptionIds + item.id)
        }
    }
}
```

Would this work?

**Comment by GrahamBorland** [comment]
@gpeal Thanks for the response. I can see how your suggestion would work for the specific case of _waiting for something to load_, but it doesn't capture the distinct Error state, and it doesn't really address the more general problem of mutually exclusive sub-states, or _actions which only make sense in certain circumstances_, which are so beautifully and elegantly represented with sealed classes. In my experience these are becoming increasingly common in the MVVM world at least.

Other examples which spring to mind:
success / error
data exists / empty
logged in / logged out

See [further discussion of this problem on Reddit](https://www.reddit.com/r/androiddev/comments/lwd5qf/mavericks_meet_jetpack_compose/gpkbjd0?utm_source=share&utm_medium=web2x&context=3).

**Comment by gpeal** [comment]
@GrahamBorland You woul make derived properties for that like:
```
enum class MyScreenDisplayState {
    Data,
    Error,
    Loading
}
data class MyScreenState(
    val data1: Async<Foo> = Unitialized,
    val data2: Async<Foo> = Uninitialized,
) {
    val displayState: DisplayState = when {
        data1() != null && data2() != null -> DisplayState.Data
        data1 is Fail || data2 is Fail -> DisplayState.Error
        else -> DisplayState.Loading
    }
}
```
You can set up when `when` however you'd like but these derived properties give you all of the benefits of a sealed top level state class without having to make your screen perfectly map to a set of distinct states which becomes extremely useful if the screen grows in functionality or your original sealed class states don't map correctly to the screen anymore.

**Comment by erikhuizinga** [comment]
Meta:

AFAIK it's impossible to formally implement a finite state machine (FSM, e.g. a `MavericksViewModel`) that can _never_ be called on an event (external, e.g. UI events or a lower layers resulting in success or failure. This can all happen _concurrently_!) that is illegal for that state. I gave this interesting issue some thought a while back and wrote it down as a response to an article here. I quote myself: https://erikhuizinga.medium.com/i-like-using-fsms-in-my-apps-c185a112a648

> [...] we enter a vicious circle: the current state defines the events that are available, but entities other than the FSM generate events that depend on the FSM being in a certain state. So, to know what events can be dispatched, you must know the current state! But only the FSM knows the current state: other entities should not keep track of the last state they read from the FSM: that would mean there's multiple places where the FSM's state lives. ... And so on, and so on.
> 
> At the end of the day: only the FSM holds state, only external classes generate events that may or may not be defined for the current state.

There is no solution to this problem other than formally/theoretically: it's possible to define FSMs with states and corresponding transitions on paper. In programming practice, I think that you'd need a different event interface for the FSM per state. That gets ugly really fast and I'm not even sure if that truly would solve the problem we're trying to solve here.

So, practically there are 2 options, both of which accept that illegal/undefined events will happen when the FSM is in a particular state:

1. Do nothing on an illegal state, effectively ignoring the event.
2. Throw an exception on an illegal state.

(something intermediate like logging an error could be a good balance between the two)

I think that this issue can be closed, because there might exist no way to perfectly and correctly implement a solution. Correct me if I'm wrong, I'd be happy to learn about a state machine pattern that doesn't have this issue and is easy to use!

**Comment by GrahamBorland** [comment]
Thanks for the interesting discussion. Either _do nothing_ or _log an error_ would work, and it's very easy to implement that ourselves. It just makes things a tiny bit more verbose.

Maybe I can get there with extensions.

**Comment by gpeal** [comment]
Thanks for sharing your thoughts @erikhuizinga. Could we close out this ticket?

**Comment by erikhuizinga** [comment]
Let me give another example of a finite state machine: a physical calculator (you know, with buttons).

In my example the calculator has a global on/off state, which can be triggered by an <kbd>ON</kbd>/<kbd>OFF</kbd> button. Then, when it's one, it has substates, e.g. if I press <kbd>ON</kbd><kbd>1</kbd><kbd>+</kbd><kbd>1</kbd><kbd>=</kbd> the calculator will happily move from an initial state through various calculation states until the final state is printed on the display: 2. However, if I generate events that are illegal/undefined for a particular state, then the calculator might just ignore them. For example: <kbd>OFF</kbd><kbd>1</kbd><kbd>+</kbd><kbd>1</kbd><kbd>=</kbd> (the only difference is that I first press the <kbd>OFF</kbd> key to turn the calculator off). Then the calculator doesn't blow up (or throw an exception); instead it just does... nothing.

In this particular example the illegal events, i.e. button presses in an off state, are simply ignored and do nothing. That is because the UI of the calculator (the interface, the buttons) permanently presents a way to input illegal events. It would be ridiculously complex to make a physical calculator that doesn't allow button inputs that aren't possible at certain moments. It might simplify things a bunch for your view models if you try to view them as calculators with permanent input buttons: some buttons really don't make sense to press in some states, but does that matter? It can, but you should likely not crash your 'calculator'.

What would a physical calculator do (or in what state would it be if I press <kbd>ON</kbd><kbd>1</kbd><kbd>+</kbd><kbd>-</kbd><kbd>*/kbd>? I don't know, but it's interesting to think about it in this way.

**Comment by gpeal** [comment]
@erikhuizinga I hear what you're saying but there are ways to achieve what you want in Mavericks.
```
fun setState(
  filter: S.() -> Boolean,
  reducer: S.() -> S,
) {
  setState { if (filter()) this else reducer }
}

fun setStateRequireOn(reducer: S.() -> S) = setState(
  filter = { isOn },
  reducer = reducer,
)
```

Other than something like that, is there a specific API you'd like to propose?

**Comment by erikhuizinga** [comment]
I'm not asking for a solution, I'm just giving an example of a state machine (physical calculator) that has well defined behaviour for illegal events (it ignores them). I hoped that my example would be understandable, so that it becomes clear that the originally posted issue is not necessarily one that must be fixed.

I think this issue can be closed, even, but that's up to maintainers/OP.

@ your example solution:
Thanks for the example. However, I wasn't asking for one; I know that ignoring/loggin/crashing on illegal events can be implemented using Mavericks. What cannot be implemented is the impossibility of certain events being sent in the first place to the VM when it's in a state that doesn't define what happens on those events. That is the original question, but AFAIK it's a logical loophole.

**Comment by GrahamBorland** [comment]
I appreciate the discussion, and accept the argument that there's no perfect solution.

What I was really looking for was an idiomatic way of expressing that certain events should be ignored when the state can't handle them, to reduce duplication and boilerplate in client code.

Something like the `filter` suggestion may work, or a `filterIsInstance` so we can benefit from type inference downstream in those cases where we do use sealed classes. I'll experiment some more.

**Comment by erikhuizinga** [comment]
To simply crash:

```
setState {
   check(this is ExpectedState)
   /* .. */
}
```

**Comment by gpeal** [comment]
I appreciate the conversation and thoughts here. I think, at this time, it doesn't seem like there is a specific change to Mavericks we'd like to make so I'm going to close this out.
