### ISSUE TITLE
App is crashing when network call returns HTTP 400.  Am I implementing this incorrectly?

### ISSUE THREAD

**Issue by martymiller** [airbnb/mavericks#659]
I'm hoping someone can help me, because I'm totally stuck.  I'm trying to capture network errors, so I'm making a network call that I know will fail.  Successful calls work fine.

I'm on Mavericks 3.0 and making a call inside my `MavericksViewModel`.  Here is my state class:

<img width="350" alt="Screen Shot 2022-10-26 at 9 40 00 AM" src="https://user-images.githubusercontent.com/3698882/198087700-ede13f02-349f-476d-af18-0940985c5576.png">

Retrofit service class call:
<img width="350" alt="Screen Shot 2022-10-26 at 9 48 34 AM" src="https://user-images.githubusercontent.com/3698882/198087924-ce21d94c-7bfb-41f2-8861-30fdb531f698.png">

Making the call inside a regular (non-suspend) function.  I tried putting this inside of a suspend {} like in the docs but the call never gets made. I set a breakpoint inside and it never lands there (don't know why).
<img width="350" alt="Screen Shot 2022-10-26 at 9 50 11 AM" src="https://user-images.githubusercontent.com/3698882/198088290-82440273-7cf8-44a6-8373-3a4a14a1818e.png">

Observing the response:
<img width="288" alt="Screen Shot 2022-10-26 at 9 50 29 AM" src="https://user-images.githubusercontent.com/3698882/198088369-9eeb392f-ee87-404f-853e-88fc8d592f73.png">

Resulting error:
<img width="1061" alt="Screen Shot 2022-10-26 at 9 49 21 AM" src="https://user-images.githubusercontent.com/3698882/198088420-3afa5896-70ee-4f0e-9c28-50573663516e.png">

After the call is made, my `authResponse` doesn't get set to LOADING or anything.  The app immediately crashes.  I don't understand why it doesn't fall into the `onFail` callback.  Is this not a `FAIL`?  If it's not then what is a FAIL when it comes to Async?  I don't want to have to put every call I make into a try / catch block.  So is there something wrong with my implementation?

**Comment by elihart** [comment]
I recommend looking at the implementation of Flow.execute
```
    protected open fun <T> Flow<T>.execute(
        dispatcher: CoroutineDispatcher? = null,
        retainValue: KProperty1<S, Async<T>>? = null,
        reducer: S.(Async<T>) -> S
    ): Job {
        val blockExecutions = config.onExecute(this@MavericksViewModel)
        if (blockExecutions != MavericksViewModelConfig.BlockExecutions.No) {
            if (blockExecutions == MavericksViewModelConfig.BlockExecutions.WithLoading) {
                setState { reducer(Loading(value = retainValue?.get(this)?.invoke())) }
            }
            // Simulate infinite loading
            return viewModelScope.launch { delay(Long.MAX_VALUE) }
        }

        setState { reducer(Loading(value = retainValue?.get(this)?.invoke())) }

        return catch { error -> setState { reducer(Fail(error, value = retainValue?.get(this)?.invoke())) } }
            .onEach { value -> setState { reducer(Success(value)) } }
            .launchIn(viewModelScope + (dispatcher ?: EmptyCoroutineContext))
    }
```

Note that this launches the flow in  the viewModelScope, so if you actually want to use IO dispatcher you need to specify that as an argument to execute. Also, it ideally wouldn't be needed to wrap the execute call in a launch call because of this, so ideally you would create your Flow without a suspend context (although that shouldn't really matter).

You can see that execute immediately does `setState { reducer(Loading(value = retainValue?.get(this)?.invoke())) }` which should set your loading state and then uses `catch { error -> setState { reducer(Fail(error, value = retainValue?.get(this)?.invoke())) } }` to catch errors and set fail states.

Based on the crash that is happening for you i'm guessing it is thrown from elsewhere, not in this flow, perhaps a mechanism of how retrofit creates its flows. I would recommend stepping through where the crash originates and looking at why it isn't part of the flow collection. It seems specific to retrofit though.

**Comment by martymiller** [comment]
Thanks @elihart I'll look into that.  I did try some other things, like making my service function non-suspend and then calling execute(IO), but then I get this error:

<img width="1144" alt="Screen Shot 2022-10-26 at 12 24 43 PM" src="https://user-images.githubusercontent.com/3698882/198118075-3ea65e49-c3e4-43f4-a544-c82cadf9a6f9.png">

I'm not sure what Retrofit changes I will need to make.  Aren't most people using Retrofit at this point?  Seems like this would be a common issue.

The API I'm using returns something like

{
  error: "Error message"
  code: "400"
}

Instead of the expected data model.  So I'm trying to figure out how to capture that message even though the response type is different.

**Comment by elihart** [comment]
@martymiller can you share the solution?
